model: gcn
in_channels: 128
out_channels: 40
d_model: 192
layers: 3
dropout: 0.5
optimizer: adam
lr: 0.01
epochs: 500
best_checkpoint_dir: checkpoints/gcn_dmodel192_best.pt
checkpoint_dir: checkpoints/gcn_dmodel192_last.pt